### PR TITLE
R6 code

### PR DESCRIPTION
**Pull request by annaw3558**
# Description

Added in code for R6 for user to buy a ticket. 
Note:
Is there a way to distinguish between user tickets and all the other tickets available. When printing a list of tickets, it just cycles through all the instances of tickets (bn.get_all_tickets()). Shouldn't there be a difference between those available for purchase and those that the users don't want to sell.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Not tested yet

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by michael-fourie** [comment]
Good job fixing the error causing the build to fail. I see that since I accidentally wrote my code in the wrong function, you wrote yours in the function I was supposed to write in. After we merge both of our pull requests, I will switch them around so that they are valid. Other than that, it seems your code ticks off all the boxes it needed for this specification.

**Review by michael-fourie — APPROVED** [review]
Good job fixing the error causing the build to fail. I see that since I accidentally wrote my code in the wrong function, you wrote yours in the function I was supposed to write in. After we merge both of our pull requests, I will switch them around so that they are valid. Other than that, it seems your code ticks off all the boxes it needed for this specification.

**Review by Slabrosse — APPROVED** [review]
This all looks good! Just that yours and Michael's buy and sell need to switch but you know this.

**Review by GabrielleGravel — APPROVED** [review]
great work. once merged this will work great

**Pull request merged**
